/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRiskRouteImport } from './routes/_app.risk'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppExplorerRouteImport } from './routes/_app.explorer'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCompareRouteImport } from './routes/_app.compare'
import { Route as AppCatalogRouteImport } from './routes/_app.catalog'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorerRoute = AppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/catalog': typeof AppCatalogRoute
  '/compare': typeof AppCompareRoute
  '/dashboard': typeof AppDashboardRoute
  '/explorer': typeof AppExplorerRoute
  '/reports': typeof AppReportsRoute
  '/risk': typeof AppRiskRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/catalog': typeof AppCatalogRoute
  '/compare': typeof AppCompareRoute
  '/dashboard': typeof AppDashboardRoute
  '/explorer': typeof AppExplorerRoute
  '/reports': typeof AppReportsRoute
  '/risk': typeof AppRiskRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/explorer': typeof AppExplorerRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/catalog'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/reports'
    | '/risk'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/catalog'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/reports'
    | '/risk'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/alerts'
    | '/_app/analytics'
    | '/_app/catalog'
    | '/_app/compare'
    | '/_app/dashboard'
    | '/_app/explorer'
    | '/_app/reports'
    | '/_app/risk'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorer': {
      id: '/_app/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AppExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppCompareRoute: typeof AppCompareRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExplorerRoute: typeof AppExplorerRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppCompareRoute: AppCompareRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExplorerRoute: AppExplorerRoute,
  AppReportsRoute: AppReportsRoute,
  AppRiskRoute: AppRiskRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
